### ISSUE TITLE
TLS mapping and extraction from host

### ISSUE THREAD

**Issue by noraj** [thecliguy/get_cipher_suites#1]
Reading [List the Supported TLS Cipher Suites on a Host](https://www.thecliguy.co.uk/2019/03/10/list-the-supported-tls-cipher-suites-on-a-host/) and [TLS Cipher Suite Naming Conventions](https://www.thecliguy.co.uk/2020/07/20/tls-cipher-suite-naming-conventions/) I can see you are interested in SSL/TLS.

So I wanted to show you a tool I created [tls-map](https://github.com/sec-it/tls-map) library in ruby.

This is a simple way to convert any OpenSSL (or GnuTLS, NSS, etc.) cipher name into IANA/standard/RFC cipher names  or hexadecimal codepoints or the other way around:

```ruby
require 'tls_map'

tm = TLSmap::App.new

# OpenSSL -> IANA
tm.search(:openssl, 'AES128-SHA', :iana) #=> {:iana=>"TLS_RSA_WITH_AES_128_CBC_SHA"}
# Hexadecimal codepoint to all (including OpenSSL & IANA)
tm.search(:codepoint, '1303') #=> {:codepoint=>"1303", :iana=>"TLS_CHACHA20_POLY1305_SHA256", :openssl=>"TLS_CHACHA20_POLY1305_SHA256", :gnutls=>"CHACHA20_POLY1305_SHA256", :nss=>"TLS_CHACHA20_POLY1305_SHA256"}
```

It's also available as a CLI tool:

```
$ tls-map search openssl AES128-SHA -o iana
iana: TLS_RSA_WITH_AES_128_CBC_SHA
```

A mapping table is maintained here: https://sec-it.github.io/tls-map/#/pages/mapping

And if you want to retrieve the ciphers from a host there are some existing tools for that: [SSLyze][1], [sslscan2][2], [testssl.sh][3], [ssllabs-scan][4]

[1]:https://github.com/nabla-c0d3/sslyze
[2]:https://github.com/rbsec/sslscan
[3]:https://github.com/drwetter/testssl.sh
[4]:https://github.com/ssllabs/ssllabs-scan

- `sslyze --json_out=example.org.json example.org`
- `sslscan2 --show-cipher-ids --xml=example.org.xml example.org`
- `testssl --jsonfile-pretty example.org.json --mapping no-openssl --cipher-per-proto example.org`
- `ssllabs-scan --quiet example.org > example.org.json`

**Comment by thecliguy** [comment]
Hi, Please accept my apologies that it has taken so long to respond. I didn't receive a notification when you logged this issue, I think this must be because I hadn't "watched" this repository. I didn't realise that as the maintainer I had to watch my own repos in order to receive notifications. Anyhow...

Thank you for letting me know about `tls-map`. I noticed that the [link to the repo](https://github.com/sec-it/tls-map) you provided has been archived. Is [this](https://github.com/noraj/tls-map) now the official repo?

**Comment by noraj** [comment]
> Thank you for letting me know about `tls-map`. I noticed that the [link to the repo](https://github.com/sec-it/tls-map) you provided has been archived. Is [this](https://github.com/noraj/tls-map) now the official repo?

Here, https://github.com/noraj/tls-map - https://noraj.github.io/tls-map/#/

**Comment by thecliguy** [comment]
Thanks for the information, much appreciated.
